/************* sym.h **************/
#define symEOF 0
#define symerror 1
#define symHEADER 2
#define symDEFINE 3
#define symTYPE 4

#define INT_CONST 5
#define FLOAT_CONST 6
#define CHAR_CONST 7
#define ID_CONST 8
#define STRING_CONST 9
#define SINGLE_COMMENT 10
#define MULTI_COMMENT 11

#define symUNDEF 12
#define STORAGE 13
#define TYPE 14
#define QUAL 15
#define ENUM 16
#define CASE 17
#define DEFAULT 18
#define IF 19
#define SWITCH 20
#define ELSE 21
#define FOR 22
#define DO 23
#define WHILE 24
#define GOTO 25
#define CONTINUE 26
#define BREAK 27
#define struct_const 28
#define RETURN 29
#define SIZEOF 30
#define WHITESPACES 31
#define ID 32
#define CHANGETYPE 33
#define FUNC 34
#define STRING 35
#define CHAR 36
#define _NULL 37